spring:
  datasource:
    url: jdbc:h2:mem:jpa;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false;AUTOCOMMIT=OFF
    driverClassName: org.h2.Driver
  jpa:
    database: h2
    properties:
      hibernate:
        format_sql: true
